import turtle
W=turtle.Turtle()
W.color('green')
canvas=turtle.screen()
canvas.bgcolor('black')
W.shape('turtle')
W.forward(10)
W.left(90)
W.forward(10)
W.left(90)
W.forward(10)
W.left(90)
W.forward(10)
W.left(90)